version: '3.8'

services:
  testingavito:
    build: ./
    command: ./testingavito
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres
    volumes:
    - ./.database/postgres/data:/var/lib/postgres/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_DB: "avito-db"
    ports:
      - 5432:5432